---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    component: istio
    installer: overrides
    app: kyma-initializer
data:
  global.proxy.includeIPRanges: '*'